server:
    port: 8081
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 1024

spring:
    main:
        allow-bean-definition-overriding: true

    datasource:
        url: ${APP_DB_URL:jdbc:postgresql://localhost:5432/n4_units}
        username: ${APP_DB_USERNAME:mnr}
        password: ${APP_DB_PASSWORD:mnrpass}
        driver-class-name: org.postgresql.Driver

    # Allows migrations to be run "out of order".
    flyway:
        out-of-order: true
        baselineOnMigrate: true
