CREATE USER mnr WITH PASSWORD 'mnrpass';

CREATE DATABASE n4_units WITH  OWNER = mnr CONNECTION LIMIT = -1;
CREATE DATABASE n4_units_test WITH  OWNER = mnr CONNECTION LIMIT = -1;

GRANT ALL PRIVILEGES ON DATABASE n4_units TO mnr;
GRANT ALL PRIVILEGES ON DATABASE n4_units TO mnr;
